Dev (#1)
* added sys import to mynmap.py. When running apt2 without the python-nmap module installed on the host, the following error is recieved:

Traceback (most recent call last):
  File "apt2.py", line 11, in <module>
    from core.framework import Framework
  File "/media/sf_Data/Tools/Dev/Ne0nd0g/apt2/core/framework.py", line 11, in <module>
    from mynmap import mynmap
  File "/media/sf_Data/Tools/Dev/Ne0nd0g/apt2/core/mynmap.py", line 4, in <module>
    sys.exit("[!] Install the nmap library: pip install python-nmap")
NameError: name 'sys' is not defined

After importing the sys library, the correct error message is displayed:

[!] Install the nmap library: pip install python-nmap

* searchftp.py module requires ftputil library. Added code to catch exception when the library isn't found on the host.

* pysmb library required for searchsmbshare.py. Added code to catch exception when the library isn't found on the host.